export const SAMPLE_REVIEWS = [
  "This product is absolutely amazing, exceeded all my expectations!",
  "Love the fast shipping and great packaging quality",
  "Outstanding quality and attention to detail, highly recommend",
  "Fantastic experience from start to finish, will buy again",
  "Best app I've ever used, intuitive and powerful features",
  "Incredible performance, runs smoothly on all my devices",
  "Perfect solution for my needs, exactly what I was looking for",
  "Excellent user interface, very easy to navigate",
  "Outstanding customer support, they really care about users",
  "Game changer! This has revolutionized how I work",
  "Beautiful design and flawless functionality",
  "Worth every penny, incredible value for money",
  "Lightning fast and reliable, never had any issues",
  "Amazing features, constantly improving with updates",
  "Professional quality, exceeded all my expectations",
  "User-friendly interface, perfect for beginners and experts",
  "Outstanding build quality, feels premium and durable",
  "Fantastic integration with other tools I use daily",
  "Incredible attention to detail, every feature is polished",
  "Best investment I've made this year, highly recommended",
  "Fast delivery and excellent packaging, very impressed",
  "Great customer service, they went above and beyond",
  "High quality materials, exactly as described",
  "Perfect fit and finish, looks exactly like the photos",
  "Excellent value for money, would definitely buy again",
  "Quick response to my questions, very helpful staff",
  "Outstanding quality control, every detail is perfect",
  "Smooth transaction from start to finish",
  "Excellent communication throughout the process",
  "Great product at a fair price, very satisfied",
  "Professional service, exceeded my expectations",
  "Fast shipping and secure packaging, very pleased",
  "High quality product, exactly what I needed",
  "Excellent customer care, they really listen to feedback",
  "Perfect condition, arrived exactly as promised",
  "Great experience overall, will definitely return",
  "Outstanding attention to detail, very impressed",
  "Excellent value, much better than expected",
  "Professional and efficient service, highly recommend",
  "Great quality and fast delivery, very happy",
  "Terrible customer service, waited 2 hours on hold for nothing",
  "Website crashed during checkout, very frustrating experience",
  "Product arrived broken and customer service was unhelpful",
  "App constantly crashes, completely unusable",
  "Waste of money, doesn't work as advertised",
  "Poor user interface, confusing and difficult to navigate",
  "Slow performance, takes forever to load anything",
  "Buggy software, crashes every few minutes",
  "Terrible support, no response to my emails",
  "Overpriced for what you get, not worth it",
  "Complicated setup, took hours to get working",
  "Frequent updates break existing features",
  "Poor documentation, impossible to figure out",
  "Unreliable service, often down when I need it",
  "Disappointing quality, feels cheap and poorly made",
  "Confusing interface, not intuitive at all",
  "Slow customer support, takes days to respond",
  "Missing key features that were promised",
  "Inconsistent performance, works sometimes",
  "Poor value for money, regret the purchase",
  "Arrived damaged, packaging was inadequate",
  "Wrong item sent, customer service was unhelpful",
  "Poor quality materials, not as described",
  "Late delivery with no communication about delays",
  "Difficult return process, took weeks to resolve",
  "Overpriced for the quality received",
  "Poor customer service, rude and unhelpful",
  "Item doesn't match the description at all",
  "Shipping was extremely slow, took over a month",
  "Poor packaging, item arrived broken",
  "Difficult to contact customer service",
  "Refund process was complicated and slow",
  "Item was used despite being sold as new",
  "Poor communication about order status",
  "Quality is much lower than expected",
  "Return policy is misleading and restrictive",
  "Customer service was dismissive of my concerns",
  "Item arrived incomplete, missing parts",
  "Poor value for money, not worth the price",
  "Overall disappointing experience, won't order again",
  "The app works fine, does what it's supposed to do",
  "Decent product for the price, nothing special though", 
  "It's okay, works as expected but could be better",
  "Functional but not particularly impressive",
  "Does the job but interface could be improved",
  "Average performance, meets basic requirements",
  "Works as advertised but nothing extraordinary",
  "Decent functionality but lacks some features I wanted",
  "It's fine for what it does, nothing more",
  "Standard quality, neither great nor terrible",
  "Meets expectations but doesn't exceed them",
  "Functional but could use some improvements",
  "Decent value for money, does what I need",
  "Works okay but not the best option available",
  "Average user experience, nothing to complain about",
  "Does what it's supposed to do, that's about it",
  "Reasonable quality for the price point",
  "Works fine but could be more user-friendly",
  "Adequate performance, nothing remarkable",
  "Standard functionality, meets basic needs",
  "Product is okay, nothing special but does the job",
  "Decent quality for the price, meets expectations",
  "Average service, nothing to complain about",
  "Works as expected, standard quality",
  "Reasonable value for money, nothing extraordinary",
  "Does what it's supposed to do, that's it",
  "Standard delivery time, no issues but nothing special",
  "Average customer service, helpful but not exceptional",
  "Decent product, meets my basic requirements",
  "It's fine, nothing to get excited about",
  "Standard quality, neither great nor poor",
  "Meets expectations but doesn't exceed them",
  "Reasonable price for what you get",
  "Works okay, does what I need it to do",
  "Average experience, nothing remarkable",
  "Decent value, nothing to complain about",
  "Standard service, meets basic requirements",
  "It's adequate, does the job",
  "Reasonable quality for the price",
  "Meets my needs but nothing more",
  "Great features but the interface needs work",
  "Love the product but shipping was slow",
  "Excellent quality but overpriced",
  "Good app but too many bugs",
  "Fast delivery but poor packaging",
  "Great customer service but product was disappointing",
  "Nice design but functionality is limited",
  "Good value but quality could be better",
  "Works well but customer support is lacking",
  "Great concept but execution needs improvement",
  "Excellent features but difficult to use",
  "Good product but terrible return policy",
  "Nice interface but performance is slow",
  "Great idea but implementation is flawed",
  "Good quality but shipping was expensive",
  "Works great but needs more features",
  "Excellent service but product was damaged",
  "Good app but too many ads",
  "Great design but functionality is basic",
  "Good value but customer service is poor"
];

export function getSampleReviewsText(): string {
  return SAMPLE_REVIEWS.join('\n');
}

export function getRandomSampleReviews(reviews: string[], count: number = 5): string {
  const shuffled = [...reviews].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count).join('\n');
}
